### ISSUE TITLE
Quotes Not Working

### ISSUE THREAD

**Issue by AmolKumarGupta** [AmolKumarGupta/portfolio#3]
Random quote in [project page](https://amol.pages.dev/projects) is not generating
If quote api is not working, then use another one

**Comment by bharatraj1508** [comment]
Hi Anmol,
I was looking into your issue that you raised. You said the random quotes not generating, what do you mean by that ?
On the UI I can see the random quotes being generated whenever the api is being hit (when you reload the page).
Do you want the quotes to be randomly generated after some timespan ?

<img width="726" alt="image" src="https://github.com/AmolKumarGupta/portfolio/assets/110130332/01f38ce6-2ff3-440d-bb78-288536475cd8">

if you reload, you can see a new quote

<img width="1446" alt="image" src="https://github.com/AmolKumarGupta/portfolio/assets/110130332/fca2eb63-51a4-481b-925d-1e65e4d8eff6">

**Comment by AmolKumarGupta** [comment]
Oh my bad, quote are not generating on my laptop.
and i thought that api is not working.
Thanks for helping me.
